const COMMANDS: &[&str] = &[
    "load_file",
    "get_volume_bounds",
    "world_to_voxel",
    "get_timeseries_matrix",
    "get_initial_views",
    "recalculate_view_for_dimensions",
    "request_layer_gpu_resources",
    "release_layer_gpu_resources",
    "fs_list_directory",
    "init_render_loop",
    "resize_canvas",
    "update_frame_ubo",
    "update_frame_for_synchronized_view",
    "set_crosshair",
    "set_view_plane",
    "render_frame",
    "create_offscreen_render_target",
    "render_to_image",
    "render_to_image_binary",
    "clear_render_layers",
    "update_layer_opacity",
    "update_layer_colormap",
    "update_layer_intensity",
    "update_layer_threshold",
    "set_layer_mask",
    "request_frame",
    "add_render_layer",
    "patch_layer",
    "sample_world_coordinate",
    "apply_and_render_view_state",
    "apply_and_render_view_state_binary",
    "apply_and_render_view_state_raw",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .build();
}