// The api-bridge command list has a single source of truth: `src/command_list.rs`
// (the `bridge_commands!` invocation). Build scripts cannot import the crate, so we
// parse that same file here with the shared parser. This keeps the Tauri plugin
// permission autogeneration (`permissions/autogenerated/`) in lockstep with the
// runtime invoke handler; the sync test in `command_registry.rs` asserts it.

include!("src/command_list_parser.rs");

fn main() {
    println!("cargo:rerun-if-changed=src/command_list.rs");
    println!("cargo:rerun-if-changed=src/command_list_parser.rs");

    let source = include_str!("src/command_list.rs");
    let commands = parse_command_list(source);
    assert!(
        !commands.is_empty(),
        "no commands parsed from src/command_list.rs"
    );

    // `tauri_plugin::Builder::new` wants `&'static [&'static str]`. The build
    // script runs once and exits, so leaking the parsed names is fine.
    let command_refs: Vec<&'static str> = commands
        .into_iter()
        .map(|name| &*Box::leak(name.into_boxed_str()))
        .collect();
    let command_refs: &'static [&'static str] = Box::leak(command_refs.into_boxed_slice());

    tauri_plugin::Builder::new(command_refs).build();
}
