const COMMANDS: &[&str] = &[
    "load_file",
    "load_surface",
    "unload_surface",
    "load_surface_overlay",
    "unload_surface_overlay",
    "get_surface_overlay_data",
    "get_surface_geometry",
    "get_volume_bounds",
    "unload_volume",
    // "world_to_voxel", // REMOVED - Unused coordinate transformation
    "set_volume_timepoint",
    "get_volume_timepoint",
    "get_volume_info",
    "get_nifti_header_info",
    "peek_volume_metadata",
    // "get_timeseries_matrix", // REMOVED - Returns unimplemented
    "get_initial_views",
    "recalculate_view_for_dimensions",
    "request_layer_gpu_resources",
    "wait_for_layer_ready",
    "release_layer_gpu_resources",
    "fs_list_directory",
    "remote_mount_connect",
    "remote_mount_respond_host_key",
    "remote_mount_respond_auth",
    "remote_mount_unmount",
    "list_remote_mount_profiles",
    "remove_remote_mount_profile",
    "init_render_loop",
    "resize_canvas",
    "update_frame_ubo",
    "update_frame_for_synchronized_view",
    "set_crosshair",
    "update_slice_outline",
    "set_view_plane",
    "create_offscreen_render_target",
    "clear_render_layers",
    "update_layer_opacity",
    "update_layer_colormap",
    "update_layer_intensity",
    "update_layer_threshold",
    "set_layer_mask",
    "request_frame",
    "add_render_layer",
    "patch_layer",
    "compute_layer_histogram",
    "sample_world_coordinate",
    "sample_layer_value_at_world",
    "get_volume_for_projection",
    "project_volume_to_surface",
    "create_surface_sampler",
    "apply_sampler",
    "release_sampler",
    "render_view", // New unified render method
    "submit_view",
    "render_views",
    "query_slice_axis_meta",
    "batch_render_slices",
    // Atlas management commands
    "get_atlas_catalog",
    "get_filtered_atlases",
    "get_atlas_entry",
    "toggle_atlas_favorite",
    "get_recent_atlases",
    "get_favorite_atlases",
    "validate_atlas_config",
    "load_atlas",
    "get_atlas_palette",
    "register_categorical_colormap",
    "load_surface_atlas",
    "start_atlas_progress_monitoring",
    "get_atlas_subscription_count",
    // Surface template commands
    "load_surface_template",
    "get_surface_template_catalog",
    // Set Studio commands
    "preview_set_studio_imports",
    "promote_discovery_to_neurotabs",
    "materialize_set_studio_compare_panes",
    "check_bids_directory",
    "scan_bids_dataset",
    "get_bids_events",
    "sample_voxel_timeseries",
    "sample_stack",
    "compute_temporal_metric",
    "compute_region_stats",
    "sample_set_at_world",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
