// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasMetadata } from "./AtlasMetadata";
import type { VolumeHandleInfo } from "./VolumeHandleInfo";

/**
 * Result of an atlas load request exposed to the frontend.
 * Wraps atlas metadata together with a concrete registered volume handle.
 */
export type AtlasLoadResult = { success: boolean, atlas_metadata: AtlasMetadata | null, 
/**
 * Convenience handle string for display/debugging (mirrors VolumeHandleInfo.id)
 */
volume_handle: string | null, 
/**
 * Rich volume handle info the UI can pass into VolumeLoadingService
 */
volume_handle_info: VolumeHandleInfo | null, 
/**
 * Present when the operation failed before a handle could be created
 */
error_message: string | null, };
