// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a loaded atlas
 */
export type AtlasMetadata = { id: string, name: string, description: string, n_regions: number, space: string, resolution: string, citation: string | null, 
/**
 * Bounding box in world coordinates
 */
bounds_mm: [[number, number, number], [number, number, number]] | null, 
/**
 * Data range for intensity values
 */
data_range: [number, number] | null, };
