// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AtlasStats = { total_layers: number, used_layers: number, free_layers: number, allocations: bigint, releases: bigint, high_watermark: number, full_events: bigint, is_3d: boolean, last_allocation_ms: bigint | null, last_release_ms: bigint | null, };
