// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Complete error information for UI display
 */
export type ErrorDisplay = { title: string, message: string, technical_details: string, suggested_actions: Array<string>, error_code: number, };
