// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistogramBin } from "./HistogramBin";

export type HistogramResult = { bins: Array<HistogramBin>, total_count: bigint, min_value: number, max_value: number, mean: number, std: number, bin_count: number, };
