// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeBounds = { min: [number, number, number], max: [number, number, number], center: [number, number, number], dims: [number, number, number], };
