// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlphaMaskMeta = { dims: [number, number, number], voxel_size: [number, number, number] | null, };
