// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque handle for an alpha mask attached to a layer (and optional timepoint).
 */
export type AlphaMaskHandle = { layer_id: string, timepoint: number | null, mask_id: bigint, };
