// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisInput } from "./AnalysisInput";

/**
 * Request payload for starting an analysis job.
 */
export type AnalysisStartRequest = { analysis_id: string, inputs: Array<AnalysisInput>, params: any, };
