// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kinds of inputs an analysis can accept.
 */
export type AnalysisInputKind = "volume" | "surface" | "surface_data" | "roi" | "file";
