// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisInputKind } from "./AnalysisInputKind";

/**
 * Concrete input instance passed to an analysis run.
 * The host may resolve handles to file paths before dispatch.
 */
export type AnalysisInput = { kind: AnalysisInputKind, 
/**
 * Optional registry handle (e.g., volume/surface id).
 */
handle: string | null, 
/**
 * Optional resolved on-disk path for sidecar runners.
 */
path: string | null, 
/**
 * Optional human-friendly name for UI display.
 */
name: string | null, 
/**
 * Arbitrary extra metadata (space, units, etc).
 */
metadata: any, };
