// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declared kinds of artifacts an analysis may produce.
 */
export type AnalysisArtifactKind = "volume" | "surface" | "surface_data" | "table" | "file" | "image2d" | "metadata";
