// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisArtifactKind } from "./AnalysisArtifactKind";

/**
 * Concrete artifact produced by an analysis job.
 */
export type AnalysisArtifact = { kind: AnalysisArtifactKind, 
/**
 * Human-friendly name for display/layer titles.
 */
name: string | null, 
/**
 * Path to artifact. For sidecars this is relative to the job output dir.
 */
path: string, 
/**
 * Optional metadata describing the artifact (space, intent, etc).
 */
metadata: any, };
