// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for batch rendering multiple slices
 */
export type BatchRenderRequest = { 
/**
 * List of view states to render (JSON serialized ViewState array)
 */
view_states_json: string, 
/**
 * Width of each slice in pixels
 */
width_per_slice: number, 
/**
 * Height of each slice in pixels
 */
height_per_slice: number, };
