// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BidsValidationIssue } from "./BidsValidationIssue";

export type BidsValidationResult = { passed: boolean, critical_count: number, warning_count: number, issues: Array<BidsValidationIssue>, };
