// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BidsTaskDesign = { task: string, trial_types: Array<string>, avg_duration_secs: number, total_runs: number, events_per_type: { [key in string]?: number }, };
