// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BidsEventRow = { onset: number, duration: number, trial_type: string, additional: { [key in string]?: string }, };
