// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BidsCoverageColumn = { session: string | null, modality: string, suffix: string, task: string | null, label: string, };
