// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary statistics for a detected cluster.
 */
export type ClusterSummary = { id: number, size_vox: number, peak_value: number, peak_ijk: [number, number, number], peak_mm: [number, number, number], centroid_ijk: [number, number, number], centroid_mm: [number, number, number], bbox_min: [number, number, number], bbox_max: [number, number, number], };
