// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlphaMaskHandle } from "./AlphaMaskHandle";
import type { ClusterSummary } from "./ClusterSummary";
import type { MaskKind } from "./MaskKind";

/**
 * Response payload when computing an alpha mask.
 */
export type ComputeAlphaMaskResult = { mask: AlphaMaskHandle, clusters: Array<ClusterSummary> | null, kind: MaskKind, };
