// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data range in the slice
 */
export type DataRange = { 
/**
 * Minimum value in the slice
 */
min: number, 
/**
 * Maximum value in the slice
 */
max: number, };
