// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a node in the file tree, optimized for flat list transfer
 */
export type FlatNode = { id: string, name: string, parent_idx: number | null, icon_id: number, is_dir: boolean, };
