// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Patch for updating layer properties
 */
export type LayerPatch = { opacity: number | null, colormap: string | null, window_center: number | null, window_width: number | null, threshold_low: number | null, threshold_high: number | null, threshold_mode: string | null, blend_mode: string | null, };
