// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content loaded from a GIFTI file
 */
export type LoadedContent = { "type": "Volume", handle: string, dimensions: [number, number, number], voxel_size: [number, number, number], } | { "type": "Surface", handle: string, vertex_count: number, face_count: number, hemisphere: string | null, surface_type: string | null, } | { "type": "SurfaceData", handle: string, data_count: number, intent: string, };
