// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification for mask provenance (extensible beyond clustering).
 */
export type MaskKind = "Cluster" | "UserDefined" | { "Other": string };
