// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single auth prompt in keyboard-interactive flow.
 */
export type RemoteAuthPrompt = { prompt: string, echo: boolean, };
