// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the remote origin backing a mounted folder.
 */
export type RemoteMountOrigin = { mount_id: string, host: string, port: number, user: string, remote_path: string, label: string, };
