// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about slices along a specific axis
 */
export type SliceAxisMeta = { 
/**
 * Total number of slices along this axis
 */
slice_count: number, 
/**
 * Spacing between slices in mm
 */
slice_spacing: number, 
/**
 * Total length of the axis in mm
 */
axis_length_mm: number, };
