// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioImportCapability = "import" | "deck" | "compare" | "materialize_compare" | "export_neurotabs";
