// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioImportReadiness = "compare_ready" | "review_required" | "inspect_only" | "blocked";
