// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioAuditSeverity } from "./StudioAuditSeverity";
import type { StudioJoinIssueDetail } from "./StudioJoinIssueDetail";

export type StudioJoinAuditSummary = { matchedRows: number, unmatchedRows: number, duplicateKeys: number, severity: StudioAuditSeverity, issueDetails: Array<StudioJoinIssueDetail>, };
