// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioFieldBindingSummary } from "./StudioFieldBindingSummary";

export type StudioMemberSummary = { id: string, sourcePath: string | null, bindings?: Array<StudioFieldBindingSummary> | null, };
