// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioDiscoveryRolePattern } from "./StudioDiscoveryRolePattern";
import type { StudioImportMode } from "./StudioImportMode";

export type StudioImportPreviewRequest = { mode: StudioImportMode, manifestPath: string | null, discoveryRoot: string | null, filePattern: string | null, tableSourceLabel: string | null, tableHeaders: Array<string> | null, tableRows: Array<Array<string>> | null, tableFilePathColumn: string | null, tableSubjectIdColumn: string | null, tableExcludedColumns: Array<string> | null, discoveryMaxDepth?: number | null, discoveryMaxFiles?: number | null, discoveryIncludePatterns?: Array<string> | null, discoveryExcludePatterns?: Array<string> | null, discoveryRequiredRoles?: Array<string> | null, discoveryRolePatterns?: Array<StudioDiscoveryRolePattern> | null, discoveryDryRun?: boolean | null, discoverySampleHeaders?: boolean | null, };
