// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioImportCapability } from "./StudioImportCapability";
import type { StudioImportProvenanceKind } from "./StudioImportProvenanceKind";
import type { StudioImportReadiness } from "./StudioImportReadiness";

export type StudioImportContract = { readiness: StudioImportReadiness, provenanceKind: StudioImportProvenanceKind, provenanceLabel: string, canImport: boolean, capabilities: Array<StudioImportCapability>, reason: string, };
