// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioFolderOntologyFactor = { name: string, source: string, values: Array<string>, confidence: number, };
