// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioFolderOntologyRoleGuess = { role: string, source: string, examples: Array<string>, confidence: number, };
