// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioFolderOntologyPreviewRequest = { root: string, maxDepth?: number | null, maxFiles?: number | null, includePatterns: Array<string>, excludePatterns: Array<string>, };
