// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioCompareBindingKind } from "./StudioCompareBindingKind";
import type { StudioCompareCacheStatus } from "./StudioCompareCacheStatus";

export type StudioComparePaneBinding = { kind: StudioCompareBindingKind, ready: boolean, sourcePath: string | null, materializationKey: string | null, materializedAtMs: bigint | null, cacheStatus: StudioCompareCacheStatus, cacheMessage: string | null, provenancePath: string | null, };
