// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioComparePaneSpec } from "./StudioComparePaneSpec";
import type { StudioMaterializationJobState } from "./StudioMaterializationJobState";

export type StudioMaterializationJobStatus = { jobId: string, state: StudioMaterializationJobState, startedAtMs: bigint | null, finishedAtMs: bigint | null, progress: number | null, message: string | null, result: Array<StudioComparePaneSpec> | null, error: string | null, };
