// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceGeometryType } from "./SurfaceGeometryType";
import type { SurfaceHemisphere } from "./SurfaceHemisphere";
import type { SurfaceSpace } from "./SurfaceSpace";

/**
 * Entry in the surface template catalog
 */
export type SurfaceTemplateCatalogEntry = { id: string, display_name: string, space: SurfaceSpace, geometry_type: SurfaceGeometryType, hemisphere: SurfaceHemisphere, vertex_count: number, };
