// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Handle for referencing a surface geometry in the registry
 */
export type SurfaceHandle = string;
