// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of loading a surface template
 */
export type SurfaceTemplateResult = { success: boolean, surface_handle: string | null, vertex_count: number | null, face_count: number | null, space: string, geometry_type: string, hemisphere: string, error_message: string | null, };
