// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error types for atlas operations
 */
export type AtlasError = { "type": "UnknownAtlas", "data": string } | { "type": "UnsupportedSpace", "data": string } | { "type": "UnsupportedResolution", "data": string } | { "type": "ValidationFailed", "data": string } | { "type": "LoadFailed", "data": string } | { "type": "AtlasNotFound", "data": string } | { "type": "InvalidParameter", "data": { field: string, value: string, } } | { "type": "IoError", "data": string } | { "type": "PathSecurityViolation", "data": string };
