// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadingStage } from "./LoadingStage";

/**
 * Progress information for atlas loading
 */
export type AtlasLoadProgress = { atlas_id: string, stage: LoadingStage, progress: number, message: string, };
