// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of an atlas
 */
export type AtlasSource = "BuiltIn" | "TemplateFlow" | "Custom";
