// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasMetadata } from "./AtlasMetadata";

/**
 * Result of successful atlas loading operation
 */
export type AtlasLoadResult = { atlas_metadata: AtlasMetadata, volume_handle: string, };
