// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Atlas type enumeration for type-safe atlas identification
 */
export type AtlasType = "schaefer2018" | "glasser2016" | "freesurfer_aseg" | "olsen_mtl" | "hippocampus";
