// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasCategory } from "./AtlasCategory";
import type { AtlasDataType } from "./AtlasDataType";
import type { AtlasSource } from "./AtlasSource";

/**
 * Filter options for atlas catalog
 */
export type AtlasFilter = { search_query: string | null, category: AtlasCategory | null, source: AtlasSource | null, space: string | null, data_type: AtlasDataType | null, show_favorites_only: boolean, show_cached_only: boolean, };
