// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Atlas category for organization
 */
export type AtlasCategory = "Cortical" | "Subcortical" | "WholeBrain" | "Specialized" | "Template";
