// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasCategory } from "./AtlasCategory";
import type { AtlasSource } from "./AtlasSource";
import type { ResolutionInfo } from "./ResolutionInfo";
import type { SpaceInfo } from "./SpaceInfo";

/**
 * Catalog entry for an atlas
 */
export type AtlasCatalogEntry = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Display name
 */
name: string, 
/**
 * Short description
 */
description: string, 
/**
 * Source of the atlas
 */
source: AtlasSource, 
/**
 * Category for organization
 */
category: AtlasCategory, 
/**
 * Compatible spaces
 */
allowed_spaces: Array<SpaceInfo>, 
/**
 * Available resolutions
 */
resolutions: Array<ResolutionInfo>, 
/**
 * For Schaefer atlases: available network counts
 */
network_options: Array<number> | null, 
/**
 * For Schaefer atlases: available parcel counts
 */
parcel_options: Array<number> | null, 
/**
 * Whether this is marked as favorite
 */
is_favorite: boolean, 
/**
 * When it was last used (ISO string)
 */
last_used: string | null, 
/**
 * Reference/citation information
 */
citation: string | null, 
/**
 * Whether atlas data is cached locally
 */
is_cached: boolean, 
/**
 * Size estimate for download
 */
download_size_mb: number | null, };
