// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration parameters for loading an atlas
 */
export type AtlasConfig = { atlas_id: string, space: string, resolution: string, 
/**
 * For Schaefer: number of networks (7 or 17)
 */
networks: number | null, 
/**
 * For Schaefer: number of parcels (100-1000)
 */
parcels: number | null, 
/**
 * Additional parameters for TemplateFlow
 */
template_params: { [key in string]?: string } | null, 
/**
 * Data type: "volume" (default) or "surface"
 */
data_type: string | null, 
/**
 * Surface type for surface atlases: "pial", "white", "inflated"
 */
surf_type: string | null, };
