// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coverage preview for a previously imported parcel-data reference.
 */
export type ParcelBindingCoveragePreview = { 
/**
 * Referenced parcel-data handle.
 */
reference_id: string, 
/**
 * Atlas identifier from payload metadata.
 */
atlas_id: string, 
/**
 * Declared parcel count from payload metadata.
 */
declared_parcel_count: number | null, 
/**
 * Number of rows in payload.
 */
parcel_row_count: number, 
/**
 * Number of unique parcel IDs in payload.
 */
unique_parcel_id_count: number, 
/**
 * Estimated matched parcel count using declared count when available.
 */
matched_parcel_count: number, 
/**
 * Percent coverage when declared count is available.
 */
coverage_percent: number | null, 
/**
 * Estimated missing parcel rows when declared count is available.
 */
estimated_missing_count: number | null, 
/**
 * Estimated extra parcel rows when declared count is available.
 */
estimated_extra_count: number | null, 
/**
 * Flattened value-column names discovered across parcel rows.
 */
value_columns: Array<string>, };
