// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for an imported parcel-data table reference.
 */
export type ParcellationReference = { 
/**
 * Stable handle used by downstream commands.
 */
reference_id: string, 
/**
 * Optional source name (e.g. filename) provided by caller.
 */
source_name: string | null, 
/**
 * Parcel-data schema version.
 */
schema_version: string, 
/**
 * Atlas identifier declared by the parcel-data payload.
 */
atlas_id: string, 
/**
 * Optional atlas display name.
 */
atlas_name: string | null, 
/**
 * Optional atlas space identity.
 */
atlas_space: string | null, 
/**
 * Optional atlas class ("volume", "surface", "both").
 */
atlas_class: string | null, 
/**
 * Declared parcel count from payload metadata.
 */
declared_parcel_count: number | null, 
/**
 * Number of parcel rows in payload.
 */
parcel_row_count: number, 
/**
 * Flattened value-column names discovered across parcel rows.
 */
value_columns: Array<string>, 
/**
 * Unix epoch timestamp (milliseconds) when imported.
 */
created_at_unix_ms: bigint, };
