// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasDataType } from "./AtlasDataType";

/**
 * Space/template information
 */
export type SpaceInfo = { id: string, name: string, description: string, data_type: AtlasDataType, };
