// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Label information for a surface atlas region
 */
export type SurfaceAtlasLabelInfo = { 
/**
 * Numeric label ID
 */
id: number, 
/**
 * Human-readable region name
 */
name: string, 
/**
 * RGB color for visualization
 */
color: [number, number, number] | null, 
/**
 * Hemisphere: "Left", "Right", or None
 */
hemisphere: string | null, 
/**
 * Network assignment name (for Schaefer)
 */
network: string | null, };
