// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParcellationReference } from "./ParcellationReference";

/**
 * Result of importing a dense surface label map as a parcellation reference.
 */
export type SurfaceLabelParcellationImportResult = { 
/**
 * Registered parcellation reference metadata.
 */
reference: ParcellationReference, 
/**
 * Number of per-vertex labels in the imported surface data.
 */
vertex_count: number, 
/**
 * Number of unique labels including background.
 */
unique_label_count: number, 
/**
 * Number of unique non-zero labels.
 */
nonzero_label_count: number, 
/**
 * Maximum label ID observed.
 */
max_label: number, 
/**
 * Background label ID (currently always zero).
 */
background_label: number, };
