// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AtlasMetadata } from "./AtlasMetadata";
import type { SurfaceAtlasLabelInfo } from "./SurfaceAtlasLabelInfo";

/**
 * Result of loading a surface atlas
 */
export type SurfaceAtlasLoadResult = { 
/**
 * Atlas metadata
 */
atlas_metadata: AtlasMetadata, 
/**
 * Per-vertex label IDs for the left hemisphere
 */
labels_lh: Array<number>, 
/**
 * Per-vertex label IDs for the right hemisphere
 */
labels_rh: Array<number>, 
/**
 * Label definitions with names, colors, networks
 */
label_info: Array<SurfaceAtlasLabelInfo>, 
/**
 * Coordinate space (e.g. "fsaverage")
 */
space: string, 
/**
 * Number of vertices in left hemisphere
 */
n_vertices_lh: number, 
/**
 * Number of vertices in right hemisphere
 */
n_vertices_rh: number, };
