// Single source of truth: every api-bridge Tauri command, listed exactly once.
//
// This file is `include!`d from `lib.rs` so the identifiers resolve in the crate
// root (analysis commands are brought into scope with a `use` in `lib.rs`, so they
// appear here as bare identifiers). It is also text-parsed by `build.rs` (see
// `command_list_parser.rs`) so the plugin permission autogeneration stays in
// lockstep with the runtime handler. The `bridge_commands!` macro expands this to
// `pub const COMMANDS` and `pub fn invoke_handler`.
//
// To add a command: add its bare identifier below, add an `allow-*` entry in
// `permissions/default.toml` (unless it is granted via a capability JSON), then run
// `cargo xtask ts-bindings`. Keep this a flat list of bare snake_case identifiers.
// Use only `//` line comments in this file: the text parser used by `build.rs`
// does not strip `/* */` block comments, so identifier-like tokens inside one
// would leak phantom commands into the permission autogeneration.
bridge_commands! {
    list_analyses,
    start_analysis,
    cancel_analysis,
    get_analysis_job_status,
    load_file,
    load_surface,
    unload_surface,
    load_surface_overlay,
    get_surface_overlay_data,
    unload_surface_overlay,
    get_surface_geometry,
    get_volume_bounds,
    unload_volume,
    set_volume_timepoint,
    get_volume_timepoint,
    get_volume_info,
    get_nifti_header_info,
    peek_volume_metadata,
    get_initial_views,
    recalculate_view_for_dimensions,
    recalculate_all_views,
    request_layer_gpu_resources,
    release_layer_gpu_resources,
    wait_for_layer_ready,
    get_atlas_stats,
    fs_list_directory,
    remote_mount_connect,
    remote_mount_respond_host_key,
    remote_mount_respond_auth,
    remote_mount_unmount,
    list_remote_mounts,
    list_remote_directory,
    list_remote_mount_profiles,
    remove_remote_mount_profile,
    init_render_loop,
    create_offscreen_render_target,
    resize_canvas,
    update_frame_ubo,
    update_frame_for_synchronized_view,
    set_crosshair,
    update_slice_outline,
    clear_render_layers,
    update_layer_opacity,
    update_layer_colormap,
    update_layer_intensity,
    update_layer_threshold,
    set_layer_mask,
    set_layer_border,
    sample_layer_value_at_world,
    get_volume_for_projection,
    project_volume_to_surface,
    create_surface_sampler,
    apply_sampler,
    release_sampler,
    request_frame,
    add_render_layer,
    patch_layer,
    compute_layer_histogram,
    sample_world_coordinate,
    render_view,
    submit_view,
    render_views,
    query_slice_axis_meta,
    batch_render_slices,
    // Atlas management commands
    get_atlas_catalog,
    get_filtered_atlases,
    get_atlas_entry,
    toggle_atlas_favorite,
    get_recent_atlases,
    get_favorite_atlases,
    validate_atlas_config,
    load_atlas,
    get_atlas_palette,
    register_categorical_colormap,
    load_surface_atlas,
    start_atlas_progress_monitoring,
    get_atlas_subscription_count,
    // Surface template commands
    load_surface_template,
    get_surface_template_catalog,
    // Template management commands
    get_template_catalog,
    get_filtered_templates,
    get_template_entry,
    validate_template_config,
    load_template,
    load_template_by_id,
    get_template_cache_stats,
    clear_template_cache,
    preview_folder_ontology,
    preview_set_studio_imports,
    promote_discovery_to_neurotabs,
    materialize_set_studio_compare_panes,
    start_set_studio_compare_materialization,
    get_set_studio_materialization_status,
    cancel_set_studio_materialization,
    check_bids_directory,
    scan_bids_dataset,
    get_bids_events,
    sample_voxel_timeseries,
    sample_stack,
    compute_temporal_metric,
    compute_region_stats,
    sample_set_at_world,
}
