use std::fs;
use std::path::Path;
#[cfg(feature = "typed-shaders")]
use std::{env, path::PathBuf};

fn main() {
    let shader_dir = Path::new("shaders");
    println!("cargo:rerun-if-changed={}", shader_dir.display());
    track_shader_sources(shader_dir);

    #[cfg(feature = "typed-shaders")]
    {
        if let Err(err) = generate_typed_shader_bindings(shader_dir) {
            panic!("failed to generate typed shader bindings: {err}");
        } else {
            println!("cargo:warning=wgsl_to_wgpu typed shader bindings generated (feature: typed-shaders)");
        }
    }

    #[cfg(not(feature = "typed-shaders"))]
    {
        // Runtime shader loading remains the default path to preserve existing behaviour.
    }
}

fn track_shader_sources(shader_dir: &Path) {
    if let Ok(entries) = fs::read_dir(shader_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |ext| ext == "wgsl") {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
}

#[cfg(feature = "typed-shaders")]
fn generate_typed_shader_bindings(shader_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    use wgsl_to_wgpu::{create_shader_module_embedded, WriteOptions};

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let generated_dir = out_dir.join("typed_shaders");
    fs::create_dir_all(&generated_dir)?;

    let shader_files = ["slice_world_space.wgsl", "slice_world_space_optimized.wgsl"];

    let write_options = WriteOptions {
        derive_bytemuck_vertex: true,
        derive_encase_host_shareable: true,
        ..Default::default()
    };

    for file in &shader_files {
        let shader_path = shader_dir.join(file);
        let source = fs::read_to_string(&shader_path)
            .map_err(|err| format!("failed to read shader '{}': {}", shader_path.display(), err))?;

        let generated = create_shader_module_embedded(&source, write_options)
            .map_err(|err| format!("wgsl_to_wgpu failed for '{}': {:?}", file, err))?;

        let output_name = file.replace('.', "_") + ".rs";
        fs::write(generated_dir.join(output_name), generated)?;
    }

    write_module_registry(&out_dir, &shader_files)?;
    Ok(())
}

#[cfg(feature = "typed-shaders")]
fn write_module_registry(
    out_dir: &Path,
    shader_files: &[&str],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut registry = String::from("// @generated by build.rs — typed shader bindings\n");

    for file in shader_files {
        let module_name = file.trim_end_matches(".wgsl");
        let file_name = file.replace('.', "_") + ".rs";
        registry.push_str(&format!(
            "pub mod {module_name} {{\n    include!(concat!(env!(\"OUT_DIR\"), \"/typed_shaders/{file_name}\"));\n}}\n"
        ));
    }

    fs::write(out_dir.join("typed_shaders.rs"), registry)?;
    Ok(())
}
