/**
 * useLayerLoading - Hook to check if a layer is currently loading
 * Integrates with LoadingQueueStore to provide consistent loading state
 */

import { useMemo } from 'react';
import { useLoadingQueueStore } from '@/stores/loadingQueueStore';

/**
 * Check if a layer is currently loading in the LoadingQueueStore
 * @param layerId - The layer ID to check for loading state
 * @returns boolean indicating if the layer is currently loading
 */
export function useLayerLoading(layerId: string): boolean {
  const activeLoads = useLoadingQueueStore(state => state.activeLoads);
  
  return useMemo(() => {
    // Check if any active load would create this layer
    for (const loadItem of activeLoads.values()) {
      if (loadItem.status === 'loading') {
        // Check if the result already indicates this layerId
        if (loadItem.result?.layerId === layerId) {
          return true;
        }
        
        // For ongoing loads, we can't easily predict the final layer ID
        // because volumeHandle.id is generated by the backend.
        // However, we can make some educated guesses:
        
        // 1. For file loads, the path might contain the layer ID
        if (loadItem.type === 'file' && loadItem.path.includes(layerId)) {
          return true;
        }
        
        // 2. For template loads, the layer ID might be related to the template ID
        if (loadItem.type === 'template') {
          // Template paths are like "template:MNI152NLin2009cAsym_T1w_1mm"
          // The layerId might be a UUID that doesn't match the template name
          // So this approach won't work well for templates
          
          // Instead, we'll rely on the completed loads having the result.layerId set
          // and fall back to the old behavior for now
        }
      }
    }
    
    return false;
  }, [activeLoads, layerId]);
}

/**
 * Alternative approach: Check by layer name or display name
 * Useful when layer ID might not be available during loading
 */
export function useLayerLoadingByName(layerName: string): boolean {
  const activeLoads = useLoadingQueueStore(state => state.activeLoads);
  
  return useMemo(() => {
    for (const loadItem of activeLoads.values()) {
      if (loadItem.status === 'loading' && loadItem.displayName === layerName) {
        return true;
      }
    }
    return false;
  }, [activeLoads, layerName]);
}

/**
 * Get loading progress for a specific layer
 * @param layerId - The layer ID to check
 * @returns Loading progress (0-100) or undefined if not loading
 */
export function useLayerLoadingProgress(layerId: string): number | undefined {
  const activeLoads = useLoadingQueueStore(state => state.activeLoads);
  
  return useMemo(() => {
    for (const loadItem of activeLoads.values()) {
      if (loadItem.status === 'loading' && loadItem.result?.layerId === layerId) {
        return loadItem.progress;
      }
    }
    return undefined;
  }, [activeLoads, layerId]);
}