// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stages of template loading
 */
export type LoadingStage = "CheckingCache" | "Downloading" | "Loading" | "Processing" | "Complete" | "Error";
