// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateResolution } from "./TemplateResolution";
import type { TemplateSpace } from "./TemplateSpace";
import type { TemplateType } from "./TemplateType";

/**
 * Filter options for template catalog
 */
export type TemplateFilter = { template_type: TemplateType | null, space: TemplateSpace | null, resolution: TemplateResolution | null, show_cached_only: boolean, };
