// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about a loaded template
 */
export type TemplateMetadata = { id: string, name: string, description: string, space: string, resolution: string, template_type: string, 
/**
 * Bounding box in world coordinates
 */
bounds_mm: [[number, number, number], [number, number, number]] | null, 
/**
 * Data range for intensity values
 */
data_range: [number, number] | null, };
