// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of brain templates available
 */
export type TemplateType = "T1w" | "T2w" | "FLAIR" | "GM" | "WM" | "CSF" | "mask" | "brain";
