// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error types for template operations  
 */
export type TemplateError = { "type": "TemplateNotFound", "data": string } | { "type": "UnsupportedSpace", "data": string } | { "type": "UnsupportedResolution", "data": string } | { "type": "UnsupportedTemplateType", "data": string } | { "type": "ValidationFailed", "data": string } | { "type": "LoadFailed", "data": string } | { "type": "DownloadFailed", "data": string } | { "type": "InvalidParameter", "data": { field: string, value: string, } } | { "type": "IoError", "data": string } | { "type": "PathSecurityViolation", "data": string } | { "type": "CacheError", "data": string };
