// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateMetadata } from "./TemplateMetadata";
import type { VolumeHandleInfo } from "./VolumeHandleInfo";

/**
 * Result of successful template loading
 */
export type TemplateLoadResult = { template_metadata: TemplateMetadata, volume_handle_info: VolumeHandleInfo, };
