// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Template coordinate spaces
 */
export type TemplateSpace = "MNI152NLin2009cAsym" | "MNI152NLin6Asym" | "fsaverage" | "fsaverage5" | "fsaverage6";
