// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Template resolutions
 */
export type TemplateResolution = "1mm" | "2mm" | "native";
