// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateResolution } from "./TemplateResolution";
import type { TemplateSpace } from "./TemplateSpace";
import type { TemplateType } from "./TemplateType";

/**
 * Configuration for loading a template
 */
export type TemplateConfig = { template_type: TemplateType, space: TemplateSpace, resolution: TemplateResolution, 
/**
 * Additional parameters for template variants
 */
params: { [key in string]?: string } | null, };
