// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache statistics information
 */
export type TemplateCacheStats = { 
/**
 * Total size of all cached files in bytes
 */
total_size_bytes: bigint, 
/**
 * Number of files in cache
 */
file_count: number, 
/**
 * List of cached template identifiers
 */
cached_templates: Array<string>, };
