// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadingStage } from "./LoadingStage";

/**
 * Progress information for template loading
 */
export type TemplateLoadProgress = { template_id: string, stage: LoadingStage, progress: number, message: string, };
