// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateConfig } from "./TemplateConfig";

/**
 * Catalog entry for a template
 */
export type TemplateCatalogEntry = { id: string, config: TemplateConfig, name: string, description: string, download_url: string | null, file_size_mb: number | null, checksum: string | null, is_cached: boolean, last_accessed: string | null, };
