// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enum to distinguish between 3D volumes and 4D time series
 */
export type VolumeType = "Volume3D" | "TimeSeries4D";
