// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPU texture format strings (matching ADR-002)
 */
export type GpuTextureFormat = "R8Unorm" | "R16Float" | "R32Float" | "RGBA8Unorm";
