// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Loaded = { "type": "Volume", "data": { dims: [number, number, number], dtype: string, path: string, } } | { "type": "Table", "data": { rows: number, cols: number, path: string, } } | { "type": "Image2D", "data": { width: number, height: number, path: string, } } | { "type": "Metadata", "data": { path: string, loader_type: string, } };
