// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlatNode } from "./FlatNode";

/**
 * The payload returned by the fs_list_directory command
 */
export type TreePayload = { nodes: Array<FlatNode>, };
