#!/usr/bin/env node

/**
 * Single-source consistency gate for the api-bridge Tauri command surface.
 *
 * The command list has one source of truth: `core/api_bridge/src/command_list.rs`
 * (the `bridge_commands!` invocation), which expands to `api_bridge::COMMANDS` and
 * the runtime invoke handler, is parsed by `build.rs` to drive permission
 * autogeneration, and is exported to `packages/api/src/generated/apiBridgeCommands.ts`
 * for the frontend transport. This script cross-checks every surface against it:
 *
 *   1. Every `#[command]` fn in `lib.rs` + `analysis.rs` appears in the command list
 *      (and vice versa) — i.e. the runtime handler covers exactly the defined commands.
 *   2. The generated transport list (`apiBridgeCommands.ts`) matches the command list.
 *   3. Every command has an autogenerated `permissions/autogenerated/commands/<cmd>.toml`,
 *      and there are no stale ones.
 *   4. Every command is granted somewhere (`default.toml` or a capability JSON), and
 *      there are no dangling `allow-*` grants for commands that no longer exist.
 *
 * Advisory by default (prints warnings). With `CI_STRICT_PERMISSIONS=1` it exits
 * non-zero when any inconsistency is found.
 *
 * Run: `node tools/check_api_bridge_permissions.mjs`
 *      `CI_STRICT_PERMISSIONS=1 node tools/check_api_bridge_permissions.mjs`
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const P = {
  libRs: path.join(ROOT, 'core', 'api_bridge', 'src', 'lib.rs'),
  analysisRs: path.join(ROOT, 'core', 'api_bridge', 'src', 'analysis.rs'),
  commandListRs: path.join(ROOT, 'core', 'api_bridge', 'src', 'command_list.rs'),
  transportTs: path.join(ROOT, 'packages', 'api', 'src', 'generated', 'apiBridgeCommands.ts'),
  defaultToml: path.join(ROOT, 'core', 'api_bridge', 'permissions', 'default.toml'),
  autogenCommandsDir: path.join(
    ROOT,
    'core',
    'api_bridge',
    'permissions',
    'autogenerated',
    'commands',
  ),
  capabilitiesDir: path.join(ROOT, 'src-tauri', 'capabilities'),
};

// Commands intentionally exempt from a specific check can be listed here.
const IGNORED_COMMANDS = new Set([]);

async function readText(filePath) {
  return fs.readFile(filePath, 'utf8');
}

/** Scan Rust source for `#[command]` / `#[tauri::command]` functions. */
function extractCommandFns(source) {
  const lines = source.split(/\r?\n/);
  const commands = new Set();
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (trimmed.startsWith('//')) continue; // skip commented-out attributes
    if (!/#\[(tauri::)?command\]/.test(trimmed)) continue;
    for (let j = i + 1; j < Math.min(lines.length, i + 10); j++) {
      const line = lines[j];
      if (line.trim().startsWith('//')) continue;
      const match = line.match(/\bfn\s+([a-zA-Z0-9_]+)\s*[(<]/);
      if (match) {
        commands.add(match[1]);
        break;
      }
    }
  }
  return commands;
}

/** Parse the bare identifiers from the `bridge_commands! { ... }` invocation. */
function parseCommandList(source) {
  // Anchor on the macro invocation so a brace in the doc-comment header cannot be
  // mistaken for the body opener.
  const anchor = Math.max(source.indexOf('bridge_commands!'), 0);
  const start = source.indexOf('{', anchor);
  const end = source.lastIndexOf('}');
  const body = start >= 0 && end > start ? source.slice(start + 1, end) : '';
  const names = new Set();
  for (const rawLine of body.split(/\r?\n/)) {
    const commentAt = rawLine.indexOf('//');
    const line = commentAt >= 0 ? rawLine.slice(0, commentAt) : rawLine;
    for (const token of line.split(',')) {
      const t = token.trim();
      if (/^[a-z_][a-z0-9_]*$/.test(t)) names.add(t);
    }
  }
  return names;
}

/** Parse command names from the generated `apiBridgeCommands.ts`. */
function parseTransportCommands(source) {
  const names = new Set();
  const re = /"([a-z_][a-z0-9_]*)"/g;
  let m;
  while ((m = re.exec(source)) !== null) names.add(m[1]);
  return names;
}

/** `allow-get-atlas-stats` -> `get_atlas_stats`. */
function allowIdToCommand(allowId) {
  return allowId.replace(/^allow-/, '').replace(/-/g, '_');
}

function commandToAllowId(cmd) {
  return `allow-${cmd.replace(/_/g, '-')}`;
}

function extractAllowCommands(source, prefix = '') {
  const commands = new Set();
  const re = new RegExp(`"${prefix}allow-[a-z0-9-]+"`, 'g');
  let m;
  while ((m = re.exec(source)) !== null) {
    const id = m[0].slice(1, -1).slice(prefix.length);
    commands.add(allowIdToCommand(id));
  }
  return commands;
}

async function listTomlBasenames(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const result = new Set();
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith('.toml')) {
      result.add(entry.name.replace(/\.toml$/, ''));
    }
  }
  return result;
}

async function capabilityGrants() {
  const grants = new Set();
  const entries = await fs.readdir(P.capabilitiesDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue;
    const src = await readText(path.join(P.capabilitiesDir, entry.name));
    for (const cmd of extractAllowCommands(src, 'api-bridge:')) grants.add(cmd);
  }
  return grants;
}

function diff(a, b) {
  return [...a].filter((x) => !b.has(x)).sort();
}

async function main() {
  const [
    libSource,
    analysisSource,
    commandListSource,
    transportSource,
    defaultTomlSource,
    autogenTomls,
    capGrants,
  ] = await Promise.all([
    readText(P.libRs),
    readText(P.analysisRs),
    readText(P.commandListRs),
    readText(P.transportTs),
    readText(P.defaultToml),
    listTomlBasenames(P.autogenCommandsDir),
    capabilityGrants(),
  ]);

  const registeredFns = new Set(
    [...extractCommandFns(libSource), ...extractCommandFns(analysisSource)].filter(
      (c) => !IGNORED_COMMANDS.has(c),
    ),
  );
  const commandList = parseCommandList(commandListSource);
  const transport = parseTransportCommands(transportSource);
  const defaultGrants = extractAllowCommands(defaultTomlSource);
  const allGrants = new Set([...defaultGrants, ...capGrants]);

  const problems = [];
  const push = (label, items) => {
    for (const item of items) problems.push(`${label}: ${item}`);
  };

  // 1. #[command] fns vs command list (the runtime handler surface).
  push(
    '#[command] fn not in command_list.rs (defined but NOT registered in the handler)',
    diff(registeredFns, commandList),
  );
  push(
    'command_list.rs entry has no #[command] fn (registered but undefined)',
    diff(commandList, registeredFns),
  );

  // 2. Command list vs generated transport surface.
  push(
    'command missing from generated apiBridgeCommands.ts (frontend calls will not be namespaced)',
    diff(commandList, transport),
  );
  push(
    'apiBridgeCommands.ts lists a non-command (stale transport entry)',
    diff(transport, commandList),
  );

  // 3. Autogenerated permission tomls.
  push(
    'command missing permissions/autogenerated/commands/<cmd>.toml',
    diff(commandList, autogenTomls),
  );
  push(
    'stale permissions/autogenerated/commands/<cmd>.toml (no such command)',
    diff(autogenTomls, commandList),
  );

  // 4. Grants (default.toml + capability JSONs).
  push(
    'command not granted in default.toml or any capability JSON',
    diff(commandList, allGrants).map((c) => `${c} (add "${commandToAllowId(c)}")`),
  );
  push('dangling allow-* grant for a non-command', diff(allGrants, commandList));

  const counts =
    `commands=${commandList.size} handlerFns=${registeredFns.size} ` +
    `transport=${transport.size} autogenTomls=${autogenTomls.size} ` +
    `defaultGrants=${defaultGrants.size} capabilityGrants=${capGrants.size}`;

  if (problems.length === 0) {
    console.log(`[check_api_bridge_permissions] OK: ${counts}`);
    return;
  }

  console.warn(`[check_api_bridge_permissions] Found ${problems.length} issue(s). ${counts}`);
  for (const p of problems) console.warn(` - ${p}`);

  if (process.env.CI_STRICT_PERMISSIONS === '1') {
    console.error(
      '[check_api_bridge_permissions] CI_STRICT_PERMISSIONS=1, treating issues as errors.',
    );
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error('[check_api_bridge_permissions] Failed:', err);
  process.exitCode = 1;
});
