#!/usr/bin/env node

/**
 * Command vs permissions inventory for core/api_bridge.
 *
 * Scans `core/api_bridge/src/lib.rs` for `#[command]` functions and verifies:
 *   1) A matching `permissions/autogenerated/commands/<cmd>.toml` exists.
 *   2) `core/api_bridge/permissions/default.toml` contains an `allow-<cmd>` entry
 *      (with `<cmd>` converted to kebab-case).
 *
 * For now this script is advisory: it prints warnings but does not fail the
 * process unless CI_STRICT_PERMISSIONS=1 is set.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const ROOT = path.resolve(__dirname, '..');
const LIB_RS = path.join(ROOT, 'core', 'api_bridge', 'src', 'lib.rs');
const COMMANDS_DIR = path.join(
  ROOT,
  'core',
  'api_bridge',
  'permissions',
  'autogenerated',
  'commands'
);
const DEFAULT_TOML = path.join(
  ROOT,
  'core',
  'api_bridge',
  'permissions',
  'default.toml'
);

// Commands that are intentionally backend-only or test-only can be added here
// to opt out of the permission check.
const IGNORED_COMMANDS = new Set([
  // 'internal_command_name',
]);

async function readText(filePath) {
  return fs.readFile(filePath, 'utf8');
}

async function listTomlBasenames(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const result = [];
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith('.toml')) {
      result.push(entry.name.replace(/\.toml$/, ''));
    }
  }
  return new Set(result);
}

function extractCommandNames(libSource) {
  const lines = libSource.split(/\r?\n/);
  const commands = new Set();

  for (let i = 0; i < lines.length; i++) {
    if (!lines[i].includes('#[command]')) continue;

    // Look ahead for the next `fn` after the #[command] attribute
    for (let j = i + 1; j < Math.min(lines.length, i + 8); j++) {
      const line = lines[j];
      const match = line.match(/\bfn\s+([a-zA-Z0-9_]+)\s*\(/);
      if (match) {
        commands.add(match[1]);
        break;
      }
    }
  }

  return commands;
}

function extractDefaultAllowIdentifiers(defaultTomlSource) {
  const identifiers = new Set();
  const re = /"allow-[^"]+"/g;
  let match;
  while ((match = re.exec(defaultTomlSource)) !== null) {
    // Strip quotes
    identifiers.add(match[0].slice(1, -1));
  }
  return identifiers;
}

function toAllowIdentifier(cmdName) {
  // sample_world_coordinate -> allow-sample-world-coordinate
  return `allow-${cmdName.replace(/_/g, '-')}`;
}

async function main() {
  try {
    const [libSource, defaultTomlSource, commandFiles] = await Promise.all([
      readText(LIB_RS),
      readText(DEFAULT_TOML),
      listTomlBasenames(COMMANDS_DIR),
    ]);

    const commandNames = extractCommandNames(libSource);
    const defaultAllowIds = extractDefaultAllowIdentifiers(defaultTomlSource);

    const warnings = [];

    for (const cmd of commandNames) {
      if (IGNORED_COMMANDS.has(cmd)) continue;

      if (!commandFiles.has(cmd)) {
        warnings.push(
          `Command '${cmd}' is missing a permissions/autogenerated/commands/${cmd}.toml entry.`
        );
      }

      const allowId = toAllowIdentifier(cmd);
      if (!defaultAllowIds.has(allowId)) {
        warnings.push(
          `Command '${cmd}' is missing default permission identifier '${allowId}' in permissions/default.toml.`
        );
      }
    }

    if (warnings.length === 0) {
      console.log(
        `[check_api_bridge_permissions] OK: ${commandNames.size} commands, all have permission files and default allow entries.`
      );
    } else {
      console.warn(
        `[check_api_bridge_permissions] Found ${warnings.length} permission issue(s):`
      );
      for (const w of warnings) {
        console.warn(` - ${w}`);
      }

      if (process.env.CI_STRICT_PERMISSIONS === '1') {
        console.error(
          '[check_api_bridge_permissions] CI_STRICT_PERMISSIONS=1, treating warnings as errors.'
        );
        process.exitCode = 1;
      }
    }
  } catch (err) {
    console.error('[check_api_bridge_permissions] Failed:', err);
    process.exitCode = 1;
  }
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
main();

